services:
  # Backend API (FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pythonchick-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:KLLeQSvrQcpHgUoJObQshpYmivXnFivO@shortline.proxy.rlwy.net:37073/railway
      - SECRET_KEY=u-know-who-am-i
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=ospanakim05@gmail.com
      - SMTP_PASSWORD=oqgx wrsp tlih qbef
      - FROM_EMAIL=ospanakim05@gmail.com
      - FROM_NAME=Pythonchick
      - FRONTEND_URL=https://pythonchik-ui.vercel.app
      - ENVIRONMENT=production
    volumes:
      - ./:/app
    command: >
      bash -c "
        python scripts/init_db.py &&
        alembic revision --autogenerate -m 'initial' || true &&
        alembic upgrade head &&
        python scripts/seed_courses.py &&
        python scripts/seed_challenges.py &&
        python scripts/seed_games.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  mysql_data: