[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "echo 'Running DB initialization...' && python scripts/init_db.py && \
                echo 'Running Alembic migrations...' && alembic upgrade head && \
                echo 'Seeding courses...' && python scripts/seed_courses.py && \
                echo 'Seeding challenges...' && python scripts/seed_challenges.py && \
                echo 'Seeding games...' && python scripts/seed_games.py && \
                echo 'Starting Uvicorn server...' && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicy = "on-failure"

[env]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"