[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python scripts/init_db.py && alembic revision --autogenerate -m \"initial\" && alembic upgrade head && python scripts/seed_courses.py && python scripts/seed_challenges.py && python scripts/seed_games.py && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicy = "on-failure"

[env]
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"
